### PR TITLE
Connection pooling

### PR DESCRIPTION
**Pull request by jpbede**
Implemented connection pooling. This work is based on your "shared-connections" branch. I've done a bit rework.

I tried also to implement a inter-process caching. But this didn't work reliable.

### CODE REVIEW

**Comment by andris9** [comment]
In general I'd like to have connection pooling, mostly for these MX servers that count connection events in addition to messages, so they might be fine with 100 connections delivering each 100 messages but reject 10 000 messages over separate connections.

The problem is that adding pooling is kind of risky as there are currently large ZoneMTA instances sending out hundreds of thousands or millions of emails to a variety of recipients (just targeting Gmail would be super easy but a bunch of random hosts in parallel is a different story) and having a bug or something in connection handling could be catastrophic. So this needs to be tested very well before actually merging.

**Comment by jpbede** [comment]
Sure. We've currently running a cluster with connection pooling. Currently we're sending just with low volume, it be we will increase it over time. We're sending to a bunch of different recipients.

**Comment by andris9** [comment]
Ok, in this case, maybe keep using connection pooling for a while and try to monitor (not sure how) how connections are handled, ie. are they properly garbage collected. The thing I fear most is that the server does not release connections properly and 1) they take up RAM 2) they take up file descriptors, so server might run out of these under heavy load.

**Comment by jpbede** [comment]
Sure i will. I'm going to add some prometheus metrics to monitor this. I keep you updated.

**Comment by jpbede** [comment]
Seems to work very well, connections getting reused and closed properly.

image

And there's also no excessive amount of FDs:

image

The FDs are for redis, queue-server and mongo. 
I will keep this running and lift the sending volume to see how it performs.

**Comment by jpbede** [comment]
After our marketing department started a campaign (80k receiver) yesterday with a bunch of different recipients on different MX i can say bit more.

The connection pooling worked very well. Connections got pooled and reused serval times. E.g. gmail connections got reused ~ 50 times without any issues.

There was no excessive use of fd's or memory, the connections gotten freed up correctly.  After and before the campaign i had the same open fd amount.

Bildschirmfoto 2020-01-16 um 17 26 07

**Comment by andris9** [comment]
Thanks!

**Comment by jpbede** [comment]
Do you also want the prometheus metrics for the connection pooling ?

**Comment by dazoot** [comment]
What about this feature ?
Do we have enough data to release it ?

**Comment by andris9** [comment]
I guess it can be released, I'll bump the major version though to discourage automatic upgrading just in case.

**Comment by dazoot** [comment]
Sounds good. Yes.

**Comment by andris9** [comment]
Released as v2.0.0. Also used the opportunity and increased minimally supported Node.js version (from 6 to 8)

**Pull request merged**
