### PR TITLE
Fixes #168: Add sender:delivered hook

### LINKED ISSUE #168: Request for a "sender:delivered" hook
Hi,

maybe i'm missing something but i don't find a hook to catch the "delivered" status of the email.

I managed to put a workaround in my testing env adding in lib/sender.js a custom hook but i think that a hook like this could be handy for many users.

If possibile could you add a sender:delivered hook right after the email is delievered to the next hop.

Thank you.

PS: 
my programming skills are low so i don't know if i did it correctly, i added

plugins.handler.runHooks('sender:delivered', [delivery, connection, err], () => false);

on row 519 of lib/sender.js

in my tests seem to work correctly.

Thank you.

### PR DESCRIPTION
**Pull request by m33ch**
Hi, as suggested by ugorey I added the hook sender:delivered in the lib/sender.js file.

Please check that everything is ok.
Thanks a lot

### CODE REVIEW

**Comment by dazoot** [comment]
This hook should include the SMTP response code.

**Comment by m33ch** [comment]
Hi @dazoot, thanks for your reply.
Sorry i don't undestand, did you mean to execute the hook only if the SMTP response code is 250 or other?

Thanks

**Comment by dazoot** [comment]
The hook should get the SMTP response string, ex:
`(250 2.0.0 Ok: queued as C343A192CBA2)`

**Comment by dazoot** [comment]
But i think it's ok because the delivery object gets the status data added to it:
```javascript
delivery.status = {
    delivered: true,
    mx: connection.options.servername || delivery.domain,
    response: bounces.formatSMTPResponse(info.response)
};
```

**Comment by andris9** [comment]
This looks like what you really need is not a new plugin hook but the already existing log hook:

```
app.addHook('log:entry', (entry, next) => {
    switch (entry.action) {
        case 'ACCEPTED':
            console.log('%s.%s delivered: %s', entry.id, entry.seq, entry.response);
            break;
        case 'REJECT':
            console.log('%s.%s failed: %s', entry.id, entry.seq, entry.response);
            break;
        case 'DEFERRED':
            console.log('%s.%s transient: %s', entry.id, entry.seq, entry.response);
            break;
    }
    next();
});
```

**Comment by m33ch** [comment]
Hi @andris9,
i have not found documentation regarding the hook log:entry, please could you give me more information?
In my plugin I need to access the "delivery" object. Is it present in the "entry" object in the log:entry hook?
Thanks

**Comment by andris9** [comment]
No, it does not include the delivery object itself but general stats (queue id, status, mx ip, local ip, smtp response etc.), in most cases there is no use of the delivery object anyway as the message has been already delivered. You can see an example of using this hook [here](https://github.com/nodemailer/zonemta-wildduck/blob/master/index.js#L587-L712)

**Comment by m33ch** [comment]
Currently i add additional information to the envelope object in a rewriteHook, which I find in the delivery object. For this reason, when the email is delivered I need to retrieve this information.
So in the hook you suggested I don't have this information.
Any suggestions?

**Comment by dazoot** [comment]
@m33ch, @andris9 just said that the `queue id, status, mx ip, local ip, smtp response etc.` is available in the `entry` object. Take it for a spin. `console.log` FTW :)

I think we can close this since the current functionality is more than enough.

**Comment by m33ch** [comment]
Of course =D but the entry object has all the info regarding the email, but not the extra info we add to the envelope during the submission that let us track the email in our external service.
Thanks about your time we will try other solution forking the repo.

**Comment by dazoot** [comment]
@m33ch you are right. In this case the `sender:delivered` hook makes sense.

**Pull request merged**
