### PR TITLE
Feature/env config

### LINKED ISSUE #292: Support setting instanceId from env variable?
Hi,

I'm setting up zonemta in a kubernetes environment; because of that it is really easy to scale up and down how many instances are running, which I'd mostly do for high availability purposes =] That said, it's much more difficult to provide a unique instanceId for each in a configuration file than it would be if I could override it in an environment variable =]

Would it be possible to add support for e.g ZMTA_INSTANCEID or similar as an environment variable that if set it would use that value instead of whatever is in the config file -- or alternatively use that unless something is in the config file?

Seems like an easy tweak but it would simplify my life greatly =]

### PR DESCRIPTION
**Pull request by taxilian**
Fixes #292 -- this is a poor man's solution, I'm sure there are better ways but it's fast, easy, and low impact =]

### CODE REVIEW

**Comment by dazoot** [comment]
Looks good to me.
+1

**Comment by dazoot** [comment]
@andris9 can we merge this in to main ?

**Comment by andris9** [comment]
Sorry, I kind of forgot about this PR.

The newest zone-mta versions allow overriding any config option with an ENV variable, including `instanceId`. The format is kind of awkward, but it should work in most cases. To use it, set an ENV variable `APPCONF_*` where `*` is the value you want to set, with dots replaced by underscores.

```
export APPCONF_queue_instanceId="ABC"
```

**Comment by dazoot** [comment]
So reject and close #292 too ?

**Pull request closed without merging**
